services:
  - type: web
    name: inventox-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: inventox-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: inventox-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: inventox-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: inventox-db
          property: password
      - key: DB_PORT
        value: 5432
      - key: DEBUG_MODE
        value: false
      - key: ENVIRONMENT
        value: production

databases:
  - name: inventox-db
    databaseName: inventox
    plan: free
    region: oregon
